### ISSUE TITLE
I2S DMA config  have pop

### ISSUE THREAD

**Issue by xinshuwei** [Analog-Devices-MSDK/msdk#195] opened 2022-10-21 15:59 UTC
i have  MAX78000 FTHR_RevA board  .I want set up max9867 codec. I learn I2S config with example.
Codec is working,i found use 

MXC_DMA_ReleaseChannel(0);
MXC_I2S_TXDMAConfig() 
This code once play is ok,but when i send a  lot of samples with “SDHC fread“  wav files, release dma ch and TXDMAConfig(), Codec play audio have pop, I have capture this audio wav with audtion（set send bu'ffer size is 1600 ,16bit two ch out,400 samples have pop）
![93114dbfe8d524da031f5874a1c861f](https://user-images.githubusercontent.com/27468495/197238464-e4b1daa7-ceaf-4522-9132-16349680f138.jpg)

How can i setup is codec with FTHR_RevA I2S ,playback a long file is not have pop? Can help me?

**Comment by Jake-Carter** [comment] 2022-11-22 21:24
Closing as duplicate of https://github.com/MaximIntegratedAI/MAX78000_SDK/issues/85

**Closed by Jake-Carter** 2022-11-22 21:24 UTC
